# Data split into training / test using sklearn train_test_split

In [27]:
import numpy as np
from sklearn.model_selection import train_test_split

In [28]:
a = np.arange(1,101)
a

array([  1,   2,   3,   4,   5,   6,   7,   8,   9,  10,  11,  12,  13,
        14,  15,  16,  17,  18,  19,  20,  21,  22,  23,  24,  25,  26,
        27,  28,  29,  30,  31,  32,  33,  34,  35,  36,  37,  38,  39,
        40,  41,  42,  43,  44,  45,  46,  47,  48,  49,  50,  51,  52,
        53,  54,  55,  56,  57,  58,  59,  60,  61,  62,  63,  64,  65,
        66,  67,  68,  69,  70,  71,  72,  73,  74,  75,  76,  77,  78,
        79,  80,  81,  82,  83,  84,  85,  86,  87,  88,  89,  90,  91,
        92,  93,  94,  95,  96,  97,  98,  99, 100])

In [29]:
b = np.arange(901,1001)
b

array([ 901,  902,  903,  904,  905,  906,  907,  908,  909,  910,  911,
        912,  913,  914,  915,  916,  917,  918,  919,  920,  921,  922,
        923,  924,  925,  926,  927,  928,  929,  930,  931,  932,  933,
        934,  935,  936,  937,  938,  939,  940,  941,  942,  943,  944,
        945,  946,  947,  948,  949,  950,  951,  952,  953,  954,  955,
        956,  957,  958,  959,  960,  961,  962,  963,  964,  965,  966,
        967,  968,  969,  970,  971,  972,  973,  974,  975,  976,  977,
        978,  979,  980,  981,  982,  983,  984,  985,  986,  987,  988,
        989,  990,  991,  992,  993,  994,  995,  996,  997,  998,  999,
       1000])

In [30]:
a_train, a_test = train_test_split(a)
a_train, a_test

(array([ 16,  52,  10,  37,  27,  86,  50,  24,   3,  82,  70,  67,  26,
          2,  72,  61,  95,  71,   8,  14,  84,  13,  18,  30,  62,  15,
         43, 100,  89,  46,  55,  11,  48,  64,  51,  45,  68,   1,  83,
         53,  19,  76,  96,  66,  94,  97,  81,  47,  25,  22,  77,   9,
         78,  32,  98,  65,  40,  36,  54,  44,  56,  85,  42,  60,  34,
         99,  92,  91,  49,  23,  35,  29,  28,  38,   6]),
 array([57, 87, 74, 33, 73,  5, 69, 41, 63, 93, 80, 58, 12, 90, 79, 75, 31,
        88, 17, 39,  4, 59, 21,  7, 20]))

In [31]:
# Default split: 75 - 25
a_train.shape, a_test.shape

((75,), (25,))

In [32]:
# Choosing a split
a_train, a_test = train_test_split(a, test_size=0.4)
a_train.shape, a_test.shape

((60,), (40,))

In [33]:
# Shuffle = False to turn off random order
train_test_split(a, shuffle = False)


[array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
        18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34,
        35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50, 51,
        52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67, 68,
        69, 70, 71, 72, 73, 74, 75]),
 array([ 76,  77,  78,  79,  80,  81,  82,  83,  84,  85,  86,  87,  88,
         89,  90,  91,  92,  93,  94,  95,  96,  97,  98,  99, 100])]

In [34]:
# random_state to get the same shuffle each time. Random_state = seed
for i in range(5):
    print(train_test_split(a, random_state=42)[1])

[84 54 71 46 45 40 23 81 11  1 19 31 74 34 91  5 77 78 13 32 56 89 27 43
 70]
[84 54 71 46 45 40 23 81 11  1 19 31 74 34 91  5 77 78 13 32 56 89 27 43
 70]
[84 54 71 46 45 40 23 81 11  1 19 31 74 34 91  5 77 78 13 32 56 89 27 43
 70]
[84 54 71 46 45 40 23 81 11  1 19 31 74 34 91  5 77 78 13 32 56 89 27 43
 70]
[84 54 71 46 45 40 23 81 11  1 19 31 74 34 91  5 77 78 13 32 56 89 27 43
 70]


In [35]:
# We can add b array in the same train_test_split 
a_train, a_test, b_train, b_test = train_test_split(a, b, test_size = 0.2, random_state=123)

In [36]:
a_train, a_test, b_train, b_test

(array([ 36,  89,  20,  30,  32,  92,  86,  10,  54,  42,  22,  91,  34,
         70,  85,  88,  96,  98,  63,  13,  21,  90,  38,  60,   2,  75,
         12,  80,  15,  55,  17,  27,  52,  46,   7,  99,  31,  45,  73,
         44,  16,  95,  19,  14,  23,  11,  59,  72,  65,   4,  41,  35,
         28,  53,   8,  49,  62,  94, 100,  40,   3,  68,  56,  50,  69,
         81,  37,  79,  97,  26,  47,  33,  74,  48,  87,  58,  84,  18,
         93,  67]),
 array([ 9, 71, 83, 29, 64,  1,  6, 51, 82,  5, 24, 66, 77, 61, 25, 43, 78,
        39, 57, 76]),
 array([ 936,  989,  920,  930,  932,  992,  986,  910,  954,  942,  922,
         991,  934,  970,  985,  988,  996,  998,  963,  913,  921,  990,
         938,  960,  902,  975,  912,  980,  915,  955,  917,  927,  952,
         946,  907,  999,  931,  945,  973,  944,  916,  995,  919,  914,
         923,  911,  959,  972,  965,  904,  941,  935,  928,  953,  908,
         949,  962,  994, 1000,  940,  903,  968,  956,  950,  969,  981,


* Note that the positions for a and b are the same!

In [37]:
a_train[:5], b_train[:5]

(array([36, 89, 20, 30, 32]), array([936, 989, 920, 930, 932]))

In [38]:
a_test[4:12], b_test[4:12]

(array([64,  1,  6, 51, 82,  5, 24, 66]),
 array([964, 901, 906, 951, 982, 905, 924, 966]))