In [22]:
import numpy as np

In [23]:
test_array = np.array([[2,11,1,9],[5,6,7,8]])

In [24]:
# test_array.sort(axis = 0)
-np.sort(-test_array, axis = -1)

array([[11,  9,  2,  1],
       [ 8,  7,  6,  5]])

In [25]:
test_array

array([[ 2, 11,  1,  9],
       [ 5,  6,  7,  8]])

In [30]:
data = np.genfromtxt("Real_estate(cleaned).csv",
                     delimiter = ';',
                     skip_header=1)
data.shape

(200, 20)

In [35]:
temp_mean = np.nanmean(data, axis = 0)
temp_mean

C:\Users\Palmg\AppData\Local\Temp\ipykernel_20652\3615647074.py:1: RuntimeWarning: Mean of empty slice
  temp_mean = np.nanmean(data, axis = 0)


array([           nan,            nan,            nan,            nan,
                  nan, 9.03787850e+02,            nan,            nan,
                  nan,            nan,            nan,            nan,
                  nan,            nan,            nan,            nan,
       3.60000000e+00,            nan,            nan, 2.70777631e+05])

In [34]:
columns_str = np.argwhere(np.isnan(temp_mean)).squeeze()
columns_str

array([ 0,  1,  2,  3,  4,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 17, 18],
      dtype=int64)

In [37]:
columns_num = np.array([5,16,19])

In [38]:
temp_fill = np.nanmax(data) + 1
temp_fill

532878.38

In [ ]:
data_num = np.genfromtxt('Real_estate(cleaned).csv',
                         delimiter = ';',
                         skip_header=1,
                         usecols=columns_num,
                         filling_values=temp_fill
                         )

2.

In [39]:
mat_A = np.array([[16,12],[34,45]])
mat_A

array([[16, 12],
       [34, 45]])

In [40]:
np.histogram2d(mat_A[0], mat_A[1], bins = 2)

(array([[0., 1.],
        [1., 0.]]),
 array([12., 14., 16.]),
 array([34. , 39.5, 45. ]))

In [41]:
np.isnan(data).sum()

3405

In [42]:
columns_num = np.argwhere(np.isnan(temp_mean) == False).squeeze()
columns_num

array([ 5, 16, 19], dtype=int64)

3.

In [45]:
arr = np.array([[12,3,4],[9,10,-3],[8,19,25]])
arr

array([[12,  3,  4],
       [ 9, 10, -3],
       [ 8, 19, 25]])

In [44]:
np.ptp(arr, axis = 0)

array([ 4, 16, 28])

In [47]:
heights = np.array([
    [162,202,175,160],
    [200,185,193,180],
    [189,181,172,168],
    [183,195,199,167]
])

In [49]:
np.percentile(heights, 75)

193.5

In [68]:
data = np.genfromtxt('Real_estate(cleaned).csv', delimiter = ';', skip_header=1, usecols=columns_str, dtype = str)
data

array([['ID_1030', 'building_1', '11.1.2005', ..., 'Home', 'No',
        'Website'],
       ['ID_1029', 'building_1', '10.1.2005', ..., 'Home', 'No',
        'Website'],
       ['ID_2002', 'building_2', '7.1.2007', ..., 'Home', 'Yes',
        'Client'],
       ...,
       ['ID_1003', 'building_1', 'nan', ..., 'nan', 'nan', 'nan'],
       ['ID_1008', 'building_1', 'nan', ..., 'nan', 'nan', 'nan'],
       ['ID_1019', 'building_1', 'nan', ..., 'nan', 'nan', 'nan']],
      dtype='<U11')

In [62]:
temp_mean = np.nanmean(data, axis = 0)
temp_mean

C:\Users\Palmg\AppData\Local\Temp\ipykernel_20652\3615647074.py:1: RuntimeWarning: Mean of empty slice
  temp_mean = np.nanmean(data, axis = 0)


array([           nan,            nan,            nan,            nan,
                  nan, 9.03787850e+02,            nan,            nan,
                  nan,            nan,            nan,            nan,
                  nan,            nan,            nan,            nan,
       3.60000000e+00,            nan,            nan, 2.70777631e+05])

In [77]:
np.unique(data[:,9], return_counts = True)

(array(['Aleksandrov', 'Ali', 'Anderson', 'Ayers', 'Bailey', 'Benitez',
        'Bennett', 'Berger', 'Blake', 'Bray', 'Bright', 'Brown',
        'Buchanan', 'Cameron', 'Campos', 'Cardenas', 'Carr', 'Carrillo',
        'Chandler', 'Charles', 'Chen', 'Choi', 'Christensen', 'Cline',
        'Co', 'Collier', 'Costa', 'Crane', 'Cross', 'Curry', 'Dorsey',
        'Edwards', 'Ellis', 'Espinoza', 'Estes', 'Ewing', 'Faulkner',
        'Ferrell', 'Fischer', 'Fisher', 'Flowers', 'Forbes', 'Franco',
        'Fritz', 'Fuller', 'Gallagher', 'Gay', 'Gibson', 'Gilbert',
        'Glass', 'Glover', 'Goodwin', 'Grant', 'Greer', 'Gross', 'Guerra',
        'Hansen', 'Hanson', 'Hatfield', 'Hendricks', 'Hess', 'Hickman',
        'Hinton', 'Hogan', 'Holland', 'Horne', 'Howard', 'Huang', 'Huff',
        'Hunt', 'Hurley', 'Irwin', 'Jensen', 'Johns', 'Juarez', 'Karenina',
        'Kennedy', 'Larsen', 'Leonard', 'Li', 'Liu', 'Lozano', 'Lucero',
        'Lynch', 'Lynn', 'Mack', 'Madden', 'Marquez', 'Mata', 'Mcconn

In [75]:
np.chararray.strip(data[:,1], 'building_')

AttributeError: module 'numpy' has no attribute 'strip'

In [81]:
np.stack((data[:,8],data[:,9]), axis = -1)

array([['Madalyn', 'Mercer'],
       ['Lara', 'Carrillo'],
       ['Donavan', 'Flowers'],
       ['Darien', 'Dorsey'],
       ['Alessandra', 'Perry'],
       ['Kaitlin', 'Owen'],
       ['Kaitlin', 'Owen'],
       ['Terry', 'Forbes'],
       ['Kole', 'Shannon'],
       ['Emmy', 'Singh'],
       ['Arabella', 'Ferrell'],
       ['Christian', 'Costa'],
       ['Michelle', 'Cameron'],
       ['Enrique', 'Cardenas'],
       ['Amanda', 'Simon'],
       ['Kamden', 'Stewart'],
       ['Skylar', 'Buchanan'],
       ['Michael', 'Juarez'],
       ['Antonio', 'Porter'],
       ['Antonio', 'Porter'],
       ['Conner', 'Huff'],
       ['Joaquin', 'Mullins'],
       ['Joaquin', 'Mullins'],
       ['Kyla', 'Walker'],
       ['Victor', 'Jensen'],
       ['Tyler', 'Carr'],
       ['Maia', 'Chandler'],
       ['Rodrigo', 'Ramirez'],
       ['Gianni', 'Fritz'],
       ['Janelle', 'Espinoza'],
       ['Julio', 'Leonard'],
       ['Melanie', 'Holland'],
       ['Gordon', 'Brown'],
       ['Jaelyn', 'Berger'

In [100]:
data = np.genfromtxt("Real_estate(cleaned).csv",
                     delimiter = ";",
                     skip_header = 1,
                     usecols=columns_str,
                     dtype = str)

In [95]:
(data[:,2] > 350000).sum()

35

In [99]:
hist, bins = np.histogram(data[:,0], bins = 5)
hist, bins

(array([ 32, 115,  34,  17,   2], dtype=int64),
 array([ 410.71 ,  717.068, 1023.426, 1329.784, 1636.142, 1942.5  ]))

In [83]:
np.nanmin(data[:,5]), np.nanmax(data[:,19])

(410.71, 532877.38)

In [87]:
data[:,11]

array(['F', 'F', 'M', 'M', 'F', 'F', 'F', 'M', 'M', 'F', 'F', 'M', 'F',
       'M', 'F', 'M', 'M', 'M', 'M', 'M', 'M', 'M', 'M', 'F', 'M', 'M',
       'F', 'M', 'M', 'F', 'M', 'F', 'M', 'F', 'F', 'F', 'M', 'F', 'M',
       'M', 'F', 'F', 'M', 'M', 'M', 'F', 'M', 'M', 'M', 'M', 'M', 'F',
       'F', 'M', 'M', 'F', 'F', 'F', 'F', 'F', 'M', 'F', 'M', 'F', 'F',
       'F', 'F', 'M', 'F', 'M', 'M', 'M', 'M', 'M', 'F', 'M', 'M', 'M',
       'F', 'F', 'M', 'M', 'M', 'F', 'F', 'M', 'M', 'M', 'M', 'F', 'F',
       'M', 'F', 'M', 'M', 'F', 'M', 'M', 'F', 'F', 'F', 'F', 'M', 'M',
       'M', 'M', 'F', 'M', 'M', 'F', 'F', 'M', 'M', 'M', 'M', 'M', 'M',
       'M', 'M', 'F', 'M', 'M', 'F', 'M', 'M', 'F', 'M', 'M', 'M', 'F',
       'M', 'M', 'F', 'F', 'M', 'F', 'M', 'M', 'M', 'F', 'F', 'F', 'M',
       'F', 'M', 'M', 'M', 'M', 'M', 'M', 'M', 'M', 'M', 'M', 'M', 'F',
       'F', 'F', 'M', 'F', 'M', 'F', 'M', 'M', 'M', 'F', 'F', 'M', 'M',
       'M', 'M', 'M', 'M', 'M', 'F', 'F', 'M', 'F', 'nan', 'nan'

In [ ]:
s = ['F', 'M']

for i in range(len(s)):
    data[:,11] = np.where(data[:,11] == s[i],
                          i,
                          data[:,11])

