In [2]:
import numpy as np

# np.empty(), np.zeros(), np.ones(), np.full()

In [3]:
# empty ndarray, give shape
arr_empty = np.empty(shape = (2,3))
arr_empty

array([[0., 0., 0.],
       [0., 0., 0.]])

In [4]:
# ndarray with zeros, give shape, can also specify datatype
arr_zeros = np.zeros(shape = (2,3),dtype = np.int8)
arr_zeros

array([[0, 0, 0],
       [0, 0, 0]], dtype=int8)

In [5]:
arr_ones = np.ones(shape = (2,3), dtype = np.int8)
arr_ones

array([[1, 1, 1],
       [1, 1, 1]], dtype=int8)

In [6]:
# ndarray with fill_value parameter
arr_full = np.full(shape = (2,3), fill_value = 2)
arr_full

array([[2, 2, 2],
       [2, 2, 2]])

In [7]:
mat_a = np.array([[1,0,9,2,2],[3,23,4,5,1], [0,2,3,4,1]])
mat_a

array([[ 1,  0,  9,  2,  2],
       [ 3, 23,  4,  5,  1],
       [ 0,  2,  3,  4,  1]])

# _like

In [8]:
# Always same shape as given argument
arr_emp_like = np.empty_like(mat_a)
arr_emp_like

array([[      0,       0,       0,       0,       0],
       [      0,       0,       0,       0,       0],
       [    916,       0,       0, 7077985,       0]])

In [9]:
# Same but with zeros
arr_zeros_like = np.zeros_like(mat_a)
arr_zeros_like

array([[0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0]])

In [10]:
# Works the same for np.ones_like or np.full_like
arr_full_like = np.full_like(mat_a, fill_value = 123)
arr_full_like

array([[123, 123, 123, 123, 123],
       [123, 123, 123, 123, 123],
       [123, 123, 123, 123, 123]])

# np.arange()

In [11]:
# range(0,30) - 1-D
array_rng = np.arange(30)
array_rng

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29])

In [12]:
# Samesame
array_rng = np.arange(start = 0, stop = 30)
array_rng

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29])

In [13]:
# Step and dtype added
array_rng = np.arange(start = 0, stop = 30, step = 3.33, dtype = np.float16)
array_rng

array([ 0.  ,  3.33,  6.66,  9.99, 13.32, 16.66, 19.98, 23.31, 26.64,
       29.97], dtype=float16)

# numpy random

In [14]:
from numpy.random import Generator as gen
from numpy.random import PCG64 as pcg

In [15]:
# Random values from normal distribution
array_RG = gen(pcg())
array_RG.normal(size = (5,5))

array([[ 1.1770244 , -0.39702607,  0.82235747,  1.28537216,  0.73971251],
       [-0.30287325,  0.51006118, -0.75981984, -0.31170982, -0.33178436],
       [ 2.0062997 ,  0.99201617, -0.21114043,  0.06851696, -1.3967579 ],
       [ 1.65717886,  2.49797739, -0.38878889, -1.71850088,  0.00341602],
       [ 0.78598567, -0.69248351,  1.03640112, -0.41437904, -0.16411696]])

In [16]:
# With seed
array_RG = gen(pcg(seed = 365))
array_RG.normal(size = (5,5))

array([[-0.13640899,  0.09414431, -0.06300442,  1.05391641, -0.6866818 ],
       [-0.50922173, -0.7999526 ,  0.73041825,  0.08825439, -2.1177576 ],
       [ 0.65526774, -0.48095012, -0.5519114 , -0.58578662, -0.98257896],
       [ 1.12378166, -1.30984316, -0.04703774,  0.955272  ,  0.26071745],
       [-0.20023668, -1.50172484, -1.4929163 ,  0.96535084,  1.18694633]])

In [17]:
array_RG.integers(10, size = (5,5))

array([[9, 3, 6, 4, 2],
       [6, 9, 2, 3, 2],
       [1, 5, 4, 4, 1],
       [3, 4, 8, 1, 6],
       [5, 0, 5, 7, 7]], dtype=int64)

In [18]:
# Integers between low and high
array_RG.integers(low = 10, high = 500, size = (5,5))

array([[184, 234,  59, 113, 426],
       [165, 172, 239, 109, 458],
       [174, 188, 494, 481, 325],
       [158, 170, 259, 309, 214],
       [184, 467,  33, 352, 454]], dtype=int64)

In [19]:
# Choose from numbers
array_RG.choice([1,2,3,4,5], size = (5,5))

array([[2, 3, 2, 1, 5],
       [5, 1, 5, 1, 5],
       [4, 4, 5, 1, 5],
       [2, 5, 1, 3, 2],
       [3, 1, 5, 2, 4]])

In [20]:
# Add probabiities
array_RG.choice([1,2,3,4,5], p = [0.1,0.2,0.3,0.2,0.2], size = (5,5))

array([[3, 3, 5, 1, 5],
       [3, 5, 2, 4, 1],
       [5, 3, 1, 3, 1],
       [2, 5, 5, 3, 5],
       [2, 5, 2, 4, 4]])

In [21]:
# Poisson lambda 1 default
array_RG.poisson(size = (5,5))

array([[0, 2, 2, 0, 0],
       [1, 0, 0, 1, 2],
       [0, 1, 0, 0, 0],
       [0, 3, 1, 0, 0],
       [1, 2, 0, 0, 0]], dtype=int64)

In [22]:
# Poisson lam parameter
array_RG.poisson(lam = 15, size = (5,5))

array([[13, 10, 15, 13, 14],
       [12, 13, 24, 16, 17],
       [16, 11, 21, 13,  7],
       [12, 14, 19, 16, 15],
       [13, 10, 11, 10, 12]], dtype=int64)

In [23]:
# Binomial distribution
array_RG.binomial(n = 100, p = 0.4, size = (5,5))

array([[46, 37, 36, 39, 39],
       [33, 41, 50, 36, 47],
       [35, 42, 40, 47, 47],
       [45, 39, 31, 41, 45],
       [44, 48, 37, 48, 45]], dtype=int64)

In [24]:
# Logistic, loc = mean, scale = standard dev
# Not the same as normal distribution though if you give (0,1) as arguments
# Logistic distribution has higher probability for extreme values, it has heavier tails
array_RG.logistic(loc = 9, scale = 1.2, size = (5,5))

array([[ 7.04935067,  7.28449296,  8.03813115,  9.8544642 ,  6.5749049 ],
       [ 7.99758016,  9.65949251,  7.85339321,  8.85294979,  7.64202919],
       [ 7.82979652, 12.23124706,  8.48659983,  7.59351125,  8.98081076],
       [ 8.10472035,  8.52410285,  5.35782964,  8.34798589,  8.95811201],
       [ 9.47469499,  9.95293094, 12.00789188, 10.92480577,  8.96692009]])

In [25]:
arr_norm1 = array_RG.normal(loc = 2, scale = 3, size = (1000))
arr_norm2 = array_RG.normal(loc = 7, scale = 2, size = (1000))
arr_log1 = array_RG.logistic(loc = 11, scale = 3, size = (1000))
arr_exp1 = array_RG.exponential(scale = 4, size = (1000))
arr_geo1 = array_RG.geometric(p = 0.7, size = (1000))

In [26]:
random_test_data = np.array([arr_norm1, arr_norm2, arr_log1, arr_exp1, arr_geo1])
random_test_data

array([[ 1.74052364,  0.17081592,  2.36441993, ..., -4.82938818,
         1.5447017 ,  0.09321197],
       [ 7.39877006,  6.55147891,  8.39100841, ...,  7.0345628 ,
         8.3348056 ,  7.76153741],
       [10.64261693, 13.98297279, 22.34603051, ..., 13.1001714 ,
         6.69012614, 15.03781235],
       [ 0.39315117,  1.26537692,  2.09902111, ...,  2.98181672,
         4.67723352,  4.35920466],
       [ 1.        ,  1.        ,  1.        , ...,  3.        ,
         2.        ,  3.        ]])

In [27]:
random_test_data.shape

(5, 1000)

In [28]:
random_test_data = random_test_data.transpose()
random_test_data

array([[ 1.74052364,  7.39877006, 10.64261693,  0.39315117,  1.        ],
       [ 0.17081592,  6.55147891, 13.98297279,  1.26537692,  1.        ],
       [ 2.36441993,  8.39100841, 22.34603051,  2.09902111,  1.        ],
       ...,
       [-4.82938818,  7.0345628 , 13.1001714 ,  2.98181672,  3.        ],
       [ 1.5447017 ,  8.3348056 ,  6.69012614,  4.67723352,  2.        ],
       [ 0.09321197,  7.76153741, 15.03781235,  4.35920466,  3.        ]])

In [29]:
random_test_data.shape

(1000, 5)

# Export to CSV

In [30]:
np.savetxt("data/random_test_from_NumPy.csv", random_test_data, fmt = "%s", delimiter = ',')

# Import back

In [31]:
np.genfromtxt("data/random_test_from_NumPy.csv", delimiter = ',')

array([[ 1.74052364,  7.39877006, 10.64261693,  0.39315117,  1.        ],
       [ 0.17081592,  6.55147891, 13.98297279,  1.26537692,  1.        ],
       [ 2.36441993,  8.39100841, 22.34603051,  2.09902111,  1.        ],
       ...,
       [-4.82938818,  7.0345628 , 13.1001714 ,  2.98181672,  3.        ],
       [ 1.5447017 ,  8.3348056 ,  6.69012614,  4.67723352,  2.        ],
       [ 0.09321197,  7.76153741, 15.03781235,  4.35920466,  3.        ]])

In [32]:
array_RG = gen(pcg(seed = 365))

arr_1 = array_RG.normal(loc = 3, scale = 2, size = (500))
arr_2 = array_RG.exponential(scale = 5, size = (500))
arr_3 = array_RG.logistic(loc = 10, scale = 4, size = (500))

array_full = np.array([arr_1,arr_2,arr_3]).transpose()
array_full.shape


(500, 3)

In [33]:
# np.loadtxt
lending_co_data_numeric_1 = np.loadtxt("data/Lending-Company-Numeric-Data.csv", delimiter=',')
lending_co_data_numeric_1

array([[ 2000.,    40.,   365.,  3121.,  4241., 13621.],
       [ 2000.,    40.,   365.,  3061.,  4171., 15041.],
       [ 1000.,    40.,   365.,  2160.,  3280., 15340.],
       ...,
       [ 2000.,    40.,   365.,  4201.,  5001., 16600.],
       [ 1000.,    40.,   365.,  2080.,  3320., 15600.],
       [ 2000.,    40.,   365.,  4601.,  4601., 16600.]])

In [34]:
# np.genfromtxt
lending_co_data_numeric_2 = np.genfromtxt("data/Lending-Company-Numeric-Data.csv", delimiter=',')
lending_co_data_numeric_2

array([[ 2000.,    40.,   365.,  3121.,  4241., 13621.],
       [ 2000.,    40.,   365.,  3061.,  4171., 15041.],
       [ 1000.,    40.,   365.,  2160.,  3280., 15340.],
       ...,
       [ 2000.,    40.,   365.,  4201.,  5001., 16600.],
       [ 1000.,    40.,   365.,  2080.,  3320., 15600.],
       [ 2000.,    40.,   365.,  4601.,  4601., 16600.]])

In [35]:
# Gen from text doesnt require dtype specification
lending_co_data_numeric_NAN = np.genfromtxt("data/Lending-Company-Numeric-Data-NAN.csv", delimiter=';')
print(lending_co_data_numeric_NAN)

# OR
print("\n-----------------------------------------------------\n")

# Loadtxt requires dtype specification if there are more than 1 dtype, for example numeric and string
lending_co_data_numeric_NAN = np.loadtxt("data/Lending-Company-Numeric-Data-NAN.csv", delimiter=';', dtype = str)
print(lending_co_data_numeric_NAN)

[[ 2000.    40.   365.  3121.  4241. 13621.]
 [ 2000.    40.   365.  3061.  4171. 15041.]
 [ 1000.    40.   365.  2160.  3280. 15340.]
 ...
 [   nan    40.   365.  4201.  5001. 16600.]
 [ 1000.    40.   365.  2080.  3320. 15600.]
 [ 2000.    40.   365.  4601.  4601. 16600.]]

-----------------------------------------------------

[['2000' '40' '365' '3121' '4241' '13621']
 ['2000' '40' '365' '3061' '4171' '15041']
 ['1000' '40' '365' '2160' '3280' '15340']
 ...
 ['' '40' '365' '4201' '5001' '16600']
 ['1000' '40' '365' '2080' '3320' '15600']
 ['2000' '40' '365' '4601' '4601' '16600']]


# partial cleaning while importing

In [40]:
# skip_header - skip n rows from too
# skip_footer - skip n rows from bottom
# usecols - what columns to include

lending_co_data_numeric_NAN = np.genfromtxt("data/Lending-Company-Numeric-Data-NAN.csv",
                                            delimiter=';',
                                            skip_header = 2,
                                            skip_footer = 2,
                                            usecols = (0,1,5))
lending_co_data_numeric_NAN

array([[ 1000.,    40., 15340.],
       [ 2000.,    40., 15321.],
       [ 2000.,    50., 13720.],
       ...,
       [ 2000.,    40., 16600.],
       [ 2000.,    40., 16600.],
       [   nan,    40., 16600.]])

In [41]:
# unpack = True - each column into its own array
lending_co_data_0, lending_co_data_1, lending_co_data_5 = np.genfromtxt("data/Lending-Company-Numeric-Data-NAN.csv",
                                            delimiter=';',
                                            skip_header = 2,
                                            skip_footer = 2,
                                            usecols = (0,1,5),
                                            unpack = True)

In [42]:
print(lending_co_data_0)
print(lending_co_data_1)
print(lending_co_data_5)

[1000. 2000. 2000. ... 2000. 2000.   nan]
[40. 40. 50. ... 40. 40. 40.]
[15340. 15321. 13720. ... 16600. 16600. 16600.]
